version: '3.1'

services:

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    restart: always

    environment:
      POSTGRES_PASSWORD: admin

#    volumes:
#      - postgres_volume:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_USER=admin
#      - POSTGRES_DB=spotinai
#volumes:
#  postgres_volume: